# This is a basic workflow to help you get started with Actions

name: nixbuild-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v10
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
    with:
      flake_directory: .
