name: nixbuild-ci

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v12
        secrets:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
        with:
          filter_builds: '.top_attr == "packages"'

      - name: Upload Nix flake to Cachix
        working-directory: .
        run: |
          nix profile install .#cachixsh
          CACHIX_AUTH_TOKEN=${{ secrets.cachix_auth_token }} cachix-push-flake-runtime-closures-all .
